require("modules.plugins.colorizer")
require("modules.plugins.completion")
require("modules.plugins.conform")
require("modules.plugins.cyberdream")
require("modules.plugins.fzf-lua")
require("modules.plugins.gitsigns")
require("modules.plugins.lint")
require("modules.plugins.lspconfig")
require("modules.plugins.lualine")
require("modules.plugins.mini")
require("modules.plugins.noice")
require("modules.plugins.snacks")
require("modules.plugins.todo-comments")
require("modules.plugins.treesitter")

-- plugins without extensive config
require("neogen").setup({})
require("which-key").setup({ preset = "helix" })
require("yazi").setup({ open_for_directories = true })
