require("modules.plugins.colorizer")
require("modules.plugins.completion")
require("modules.plugins.conform")
require("modules.plugins.cyberdream")
require("modules.plugins.fidget")
require("modules.plugins.gitsigns")
require("modules.plugins.inc-rename")
require("modules.plugins.incline")
require("modules.plugins.indent-blankline")
require("modules.plugins.lspconfig")
require("modules.plugins.lualine")
require("modules.plugins.mini")
require("modules.plugins.oil")
require("modules.plugins.telescope")
require("modules.plugins.todo-comments")
require("modules.plugins.treesitter")

-- plugins without extensive config
require("neogen").setup({})
require("which-key").register({})
